# Generated by Django 5.0.6 on 2024-07-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(max_length=20)),
                ('end_time', models.TimeField()),
                ('courses', models.CharField(max_length=25)),
                ('classroom', models.TextField()),
                ('day_of_the_week', models.TextField()),
            ],
        ),
    ]
