# Generated by Django 5.0.6 on 2024-06-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='last_name_name',
            new_name='last_name',
        ),
    ]
